s3: 
    bucket_name: "physicianconversionbucket"
    file_path: "Input_data.csv"
    aws_region : 'eu-north-1'  # Replace with your desired AWS region

preprocessed:
    preprocessed_df_path: 'preprocessed/preprocessed_df.csv' 
    x_test: 'preprocessed/x_test.csv'
    y_test: 'preprocessed/y_test.csv'
    encoders_path: 'preprocessed/encoders.pkl'
    model_variable_list_file_path: "preprocessed/"
    model_variable_list_file_name: "top_n_list_selectKbest.pkl"
    train_df_path: "train/train.csv"
    inference_df_path: "inference/inference.csv"

feature_transformation:
    drop_column_list : ['HCO_Affiliation']
    one_hot_encode_feature_list :  ['Sex', 'Specialty', 'HCO_Affiliation_Type']
    id_target_col_list : ['NPI_ID', 'HCP_ID', 'TARGET']
    id_col_list : ['NPI_ID', 'HCP_ID']
    target_col : ['TARGET']

param_values:
    variance_threshold_value : 0.1
    select_k_best_feature_num : 30


hopsworks_feature_store:
    api_key: "Opj3Q11E9l2J6Gl5.cWuMNUBKBrRs7L966VMGIf2DMgrm753CJhZ93RxMTuW93a9fvC9fHzytjl3bnkME"
    project_name: "MlopsLearning"
    table_name: "physician_conversion_feature_store"
    lookup_key: c
    label : ['TARGET']
    description : "Physician conversion features- claims, procedure, demographic, etc."
    feature_view: "physician_conversion_feature_view"


train_model_parameters:
    inference_size: 0.1
    params: {'gamma': 0.00023319791958746405, 'max_depth': 7, 'reg_alpha': 0.15675207826030843, 'subsample': 0.21510351218256185}

    
