name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt


      - name: List Subdirectories and Contents Recursively
        run: |
          ls -R

      - name: Debug Output
        run: |
          ls -l  # List the current directory contents
          pwd    # Print the current working directory
          echo "Checking if feature_pipepline.yml exists: $(ls ./conf/tasks/feature_pipepline.yml)"

      - name: Run feature Python Script
        run: python physician_conversion_model/tasks/feature_pipeline.py

